name: "build"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:

  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Dev build
        run: make dev

      - name: Release build
        run: make

      - name: Install
        run: sudo make install

      - name: Uninstall
        run: sudo make uninstall
