name: "release"

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify
        run: |
          ./script/check_release.sh

  release:
    needs: [build, check]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish
        run: |-
          cargo publish \
            --token "${{ secrets.CRATES_IO_TOKEN }}"
