name: "release"

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify
        run: |
          git_version=`git describe --tags HEAD | sed -e 's/^v//'`
          toml_version=`sed -n 's/^version\s*=\s*"\(.*\)"/\1/p' Cargo.toml | head -1`
          rst_version=`sed -n 's/^:Footer: reclog \(.*\)/\1/p' MANUAL.rst`
          troff_version=`sed -n 's/.TH .* "reclog \(.*\)"/\1/p' reclog.1`
          if [[ "$git_version" != "$toml_version" || "$git_version" != "$rst_version" \
                || "$git_version" != "$troff_version" ]]; then
            echo "Version mismatch detected!"
            echo "  Git tag:     $git_version"
            echo "  Cargo.toml:  $toml_version"
            echo "  MANUAL.rst:  $rst_version"
            echo "  reclog.1:    $troff_version"
            exit 1
          fi

  release:
    needs: [build, check]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish
        run: |-
          cargo publish \
            --token "${{ secrets.CRATES_IO_TOKEN }}"
